DISABLE_AUTO_UPDATE="true"
DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_COMPFIX="true"
ZSH_THEME="agnoster"
export ZSH="$HOME/.oh-my-zsh"

plugins=()

source $ZSH/oh-my-zsh.sh

# Historial
HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt EXTENDED_HISTORY          # guarda timestamp a cada comanda
setopt HIST_EXPIRE_DUPS_FIRST    # elimina duplicats primer quan cal fer espai
setopt HIST_IGNORE_DUPS          # no guarda duplicats consecutius
setopt HIST_IGNORE_ALL_DUPS      # elimina duplicats antics si n'hi ha un de nou
setopt HIST_FIND_NO_DUPS         # no mostra duplicats en cerques
setopt HIST_SAVE_NO_DUPS         # no guarda duplicats al fitxer
setopt SHARE_HISTORY             # comparteix historial entre sessions

# Fuzzy search per prefix amb fletxes amunt/avall (ex: git + ↑ = comandos git)
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

# Plugins (via Homebrew)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE="20"
ZSH_AUTOSUGGEST_USE_ASYNC=1
[ -f /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Custom
export CODE_PATH="$HOME/Projects"
source ~/.zsh/git.zsh
source ~/.zsh/general.zsh
export PATH="$HOME/.local/bin:$PATH"
